export const services=[
{slug:"binnenschilderwerk",title:"Binnenschilderwerk",tag:"Een frisse blik op uw interieur",text:"Van een enkele deur tot een complete woning: zorgvuldig schilderwerk maakt het verschil. Wij schilderen wanden, plafonds, kozijnen en deuren met aandacht voor een rustige, nette afwerking.",items:["Wanden en plafonds","Kozijnen en deuren","Woonkamers en keukens","Complete woningen"],extra:"We bespreken de gewenste kleuren en afwerking, beschermen de omgeving en bereiden de ondergrond zorgvuldig voor. Zo krijgt uw interieur een verzorgde uitstraling, terwijl we rekening houden met het dagelijks gebruik van uw woning."},
{slug:"buitenschilderwerk",title:"Buitenschilderwerk",tag:"Mooi van buiten. Goed beschermd.",text:"Uw buitenwerk krijgt heel wat te verduren. Goed schilderwerk geeft uw woning een verzorgde uitstraling en beschermt houtwerk tegen zon, regen en wisselende temperaturen.",items:["Buitenkozijnen en deuren","Dakkapellen","Gevelonderdelen","Schuren en buitenhoutwerk"],extra:"Een goed resultaat begint bij de ondergrond. We bespreken de staat van het bestaande schilderwerk, de benodigde voorbereiding en een passende afwerking. De uitvoering plannen we met oog voor de weersomstandigheden."},
{slug:"onderhoudsschilderwerk",title:"Onderhoudsschilderwerk",tag:"Goed onderhoud begint op tijd",text:"Tijdig onderhoud helpt houtwerk en andere onderdelen langer in goede staat te houden. We bekijken wat aandacht nodig heeft en bespreken welke werkzaamheden passend zijn.",items:["Controle van bestaand schilderwerk","Voorbereiding van de ondergrond","Onderhoud van houtwerk","Binnen- en buitenonderhoud"],extra:"Bladderende verf of open naden zijn signalen om onderhoud te bespreken. Door schilderwerk op tijd bij te werken, helpt u grotere schade en herstelkosten voorkomen. Wij geven een duidelijke prijsopgave voor de afgesproken werkzaamheden."},
{slug:"behangen",title:"Behangen",tag:"Een wand met karakter",text:"Van een rustige basis tot een opvallende accentwand: behang geeft een interieur een eigen sfeer. Wij zorgen voor zorgvuldig behangwerk en een nette afwerking.",items:["Woonkamers en slaapkamers","Accentwanden","Voorbereiding van wanden","Nette aansluitingen en afwerking"],extra:"Vertel ons welk behang u wilt laten aanbrengen en hoe de wanden er nu uitzien. Samen bespreken we de voorbereiding, de materialen en de uitvoering. Ook wanneer u behangwerk wilt combineren met schilderwerk kunt u contact opnemen."}];
export const reviews=[
{name:"Dirk",date:"30 april 2018",work:"Schilderwerk woning",text:"Dirk beschrijft het schilderwerk aan zijn woning als vakwerk en beveelt het bedrijf aan."},
{name:"Mevr. Visser",date:"13 oktober 2017",work:"Woning",text:"Deze klant uit Gouda is erg tevreden en noemt de schilders netjes en vriendelijk."},
{name:"Jan de Pater",date:"12 juni 2017",work:"Woning · Waddinxveen",text:"Jan kwam via vrienden bij het bedrijf terecht. Hij is positief over de schilders en de nette uitvoering."},
{name:"Jorn Loomans",date:"3 september 2016",work:"Kozijnen, deuren en schuur",text:"Jorn waardeert het vakmanschap en de schone oplevering. Hij maakte daarna een afspraak voor binnenwerk."},
{name:"Bart en Marianne",date:"16 februari 2016",work:"Schilderwerk",text:"Deze klanten noemen het advies, de precieze werkwijze en het nakomen van afspraken als sterke punten."},
{name:"Miranda Verbaan",date:"14 januari 2016",work:"Keuken",text:"Miranda bedankt het bedrijf voor de service en is blij met de opgeknapte keuken."}];
export const projects=[{title:"Kozijnen & deuren",category:"Buiten",tags:["Buiten","Kozijnen & deuren","Woningen"],text:"Buitenschilderwerk aan kozijnen en deuren van een woning en schuur."},{title:"Een complete woning",category:"Binnen",tags:["Binnen","Woningen"],text:"Schilderwerk aan kozijnen, deuren en plafonds in een complete woning."},{title:"Een frisse keuken",category:"Keukens",tags:["Binnen","Keukens","Woningen"],text:"Een keuken opnieuw schilderen voor een frisse uitstraling."},{title:"Dakkapel opknappen",category:"Buiten",tags:["Buiten","Woningen"],text:"Een dakkapel een verzorgde uitstraling geven."},{title:"Schilderwerk op kantoor",category:"Zakelijk",tags:["Binnen","Zakelijk"],text:"Een nette afwerking van een kantoorinterieur."}];
